<a href="https://colab.research.google.com/github/KRISHNAKANTH2003/CodeSoft/blob/main/Copy_of_Welcome_To_Colaboratory.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
data = pd.read_csv('dialogs.csv')

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(data['input'], data['output'], test_size=0.2, random_state=42)

# New Section

In [ ]:
vectorizer = TfidfVectorizer()
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

In [ ]:
model = MultinomialNB()
model.fit(X_train_tfidf, y_train)

MultinomialNB()

In [ ]:
y_pred = model.predict(X_test_tfidf)

In [ ]:
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
                                                                                   precision    recall  f1-score   support

                               it doesn't matter. here he comes now with the mop.       0.00      0.00      0.00         1
                                                                          $1,000.       0.00      0.00      0.00         1
                                     a blind date doesn't mean that she is blind!       0.00      0.00      0.00         1
                       a button is hard to find. did you look in your pant cuffs?       0.00      0.00      0.00         1
                                                          a couple of months ago.       0.00      0.00      0.00         1
                                                                    a luxury car.       0.00      0.00      0.00         1
                  

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
def chatbot(input_text):
    input_text_tfidf = vectorizer.transform([input_text])
    predicted_output = model.predict(input_text_tfidf)
    return predicted_output[0]

In [ ]:
while True:
    user_input = input("You: ")
    if user_input.lower() == "quit":
        break
    chatbot_response = chatbot(user_input)
    print("Chatbot: ", chatbot_response)

You: hi
Chatbot:  what do you mean?
You: hellow
Chatbot:  what do you mean?
You: qiut
Chatbot:  what do you mean?
You: quit
